### PR TITLE
Support moment loaded via Node

### PR DESCRIPTION
**Pull request by kitbrennan90**
In Node, moment is loaded via the 'global' object instead of the 'window' object. This change checks which object moment is loaded on, and uses the appropriate object.

Fixes the following issue: https://github.com/urish/angular-moment/issues/79

### CODE REVIEW

**Comment by urish** [comment]
Hi, thanks for the contribution! 

Please apply the `global` patch at [line 561](https://github.com/urish/angular-moment/blob/master/angular-moment.js#L561) instead.

**Comment by kitbrennan90** [comment]
Hi urish, no problem - this should now be fixed.

**Comment by urish** [comment]
Thanks!

**Comment by urish** [comment]
Released as 0.10.2

**Pull request merged**
