### PR TITLE
Fix for "Electron"

### PR DESCRIPTION
**Pull request by gantrior**
Hi, angular-moment does not load in Electron "renderer" environment. It is because 
`module` and `module.exports` exists in Electron environment, but the followed code does not 
<pre>angularMoment(require('angular'), require('moment'));
module.exports = 'angularMoment';</pre>

code bellow works for me

### CODE REVIEW

**Comment by urish** [comment]
Thanks for the PR!

I believe that commit 517f42f should solve this. Can you please check and confirm?

**Comment by gantrior** [comment]
Nope, does not work on Electron. `(typeof require === 'function')` is evaluated as True in Electron renderer environment, so the call falls into `module.exports = angularMoment(require('angular'), require('moment'))` which does not

My PR is based on the [issue](https://github.com/electron/electron/issues/2288) where is solved how to detect Electron environment, and it works quite well

**Comment by urish** [comment]
Got it! Can you please update the PR for the latest code version?

**Comment by gantrior** [comment]
rebased on the latest changes (release 1.0.0)

**Comment by urish** [comment]
Thanks!

**Pull request merged**
