### PR TITLE
Added support for nw.js

### PR DESCRIPTION
**Pull request by makkesk8**
Added a check to see if moment is defined, if its not, try to require it using browserify / nw.js native require

### CODE REVIEW

**Comment by urish** [comment]
Thanks! Can you please make sure that tests / jshint pass?

**Comment by makkesk8** [comment]
Embarrassing PR :/

**Comment by urish** [comment]
No worries, it is your first contribution to this project :)

Just one request - can you rename `IsUsingRequire` to something like `requireMoment`?

1. `IsUsingRequire` is not a class name, so it should be start with a lowercase letter, like the rest of the functions in the code (and then you won't have to place `new` next to it to make jshint happy)
2. starting it with the word `is` usually indicates that it returns a boolean. Therefore, I believe using a var (such as `require`) makes it much easier to understand the purpose of the function when reading the code.

I hope that you are okay with the feedback :)

Thanks!

**Comment by makkesk8** [comment]
> Just one request - can you rename IsUsingRequire to something like requireMoment?

Ofc, I did this really quick and didn't really think much of it.

> IsUsingRequire is not a class name, so it should be start with a lowercase letter, like the rest of the functions in the code (and then you won't have to place new next to it to make jshint happy)

I had no idea, thank you!

> starting it with the word is usually indicates that it returns a boolean. Therefore, I believe using a var (such as require) makes it much easier to understand the purpose of the function when reading the code.

Right :)

> I hope that you are okay with the feedback :)

All feedback is good feedback :)

**Pull request closed without merging**
