### PR TITLE
A filter to add or subtract a value from a given date using the methods Add and Subtract

### PR DESCRIPTION
**Pull request by nicholasruggeri**
Pull request for issue #170.

### CODE REVIEW

**Comment by urish** [comment]
Looks good, thanks!

Can you please:
1. Rename them to `amAdd`, `amSubtract` to keep it consistent with the other filters
2. Add tests for them

Thanks!

**Comment by nicholasruggeri** [comment]
Thank you @urish ;)
All done.

**Comment by urish** [comment]
Thanks!

**Comment by urish** [comment]
p.s. I have improved the tests, they now explicitly state the expected result as you originally intended to do:

		it('should subtract 1 hour from date', function () {
			var date = new Date(2000, 1, 1, 0, 0, 0);
			expect(amSubtract(date, 1, 'hours').toString()).toMatch(/^Mon Jan 31 2000 23:00:00/);
		});

**Comment by urish** [comment]
Released as 0.10.3

**Pull request merged**
