### PR TITLE
fix(exports): fix export for webpack (commonjs)

### LINKED ISSUE #108: cannot use angular-moment under webpack
I'm running an angular app under webpack-dev-server that includes moment and angular moment. My basic config file stars as:

```javascript
var app;

require("jquery");
require("angular");
require("ui_router");
require("facebook");
require("bootstrap_css");
require("index_scss");
require("ui_bootstrap");
require("angular_mocks");
require("angular_sanitize");
require("moment");
require("angular_moment");

mockApp = angular.module('mockApp', ['sp.app', 'ngMockE2E'])
.run (['$httpBackend',
    function($httpBackend) {
        server_url = 'https://dev.sharepractice.com';
        $httpBackend.whenGET(server_url + '/api/v1/specialties_list')
            .respond({
                results: ['Voodoo', 'Acupuncture and Oriental Medicine', 'Addiction Medicine', 'Functional Medicine']
            });
        $httpBackend.whenGET(/.*/).passThrough();
        $httpBackend.whenPOST(/.*/).passThrough();
    }
]);

app = angular.module("sp.app", ['ui.router', 'ui.bootstrap', 'facebook', 'mockApp', 'ngSanitize', 'angularMoment'])
```

I get a javascript error when angular-moment loads that "angular.moment" is not a function.

I investigated this and found that, for some reason, when angular-moment is intializing, the passed in value for angular is an empty object (not null/undefined but an empty object). I fixed the problem in my local source for angular-moment by adding a check for an empty angular object at which point I assign angular the value of window.angular (which does exist). This fixes the issue, but, as is, angular-moment will not work with my app otherwise...

My modification:
before the line #20 in angular-moment.js v0.9.0, I insert this block

```javascript
var angularAvailable = false;
for (prop in angular) {
	angularAvailable = true;
}

if (!angularAvailable) {
	angular = window.angular;
}
```

### PR DESCRIPTION
**Pull request by aaronroberson**
I read the contributing document. . .

Here is my webpack.config.js file if it helps:

```
{
    entry: {
      app: './src/app.js'
    },
    output: {
      filename: 'app.js'
    },
    watch: watch,
    devtool: (process.env.NODE_ENV === 'production') ? 'source-map' : 'inline-source-map',
    module: {
      preLoaders: [{test: /\.js$/, exclude: [/node_modules/, /bower_components/], loader: 'jshint'}],
      loaders: [
        {test: /\.js$/, exclude: [/node_modules/, /bower_components/], loader: 'babel', query: {
          // https://github.com/babel/babel-loader#options
          cacheDirectory: true,
          presets: ['es2015', 'stage-0', 'stage-1', 'stage-2'],
          plugins: ['transform-es2015-modules-commonjs']
        }},
        {test: /\.css$/, loader: 'style!css!postcss'},
        {test: /\.json$/, exclude: [/node_modules/, /bower_components/], loader: 'json'},
        {test: /[\/]angular\.js$/, exclude: [/bower_components/], loader: 'exports?angular'}
      ]
    },
    postcss: [autoprefixer({ browsers: ['last 2 version'] })],
    plugins: [
      new BowerWebpackPlugin({
        exclude: [
          /.*angular*/,
          /.*angular-cookies*/,
          /.*angular-sanitize*/,
          /.*angular-resource*/,
          /.*angular-messages*/,
          /.*angular-translate*/,
          /.*angular-touch*/,
          /.*angular-mocks*/,
          /.*jquery*/,
          /.*bootstrap-sass-official\/.*\.js/,
          /.*bootstrap\.css/,
          /.*awesome-bootstrap-checkbox*/,
          /.*font-awesome*/,
          /.*\.less/
        ],
        searchResolveModulesDirectories: false
      }),
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery',
        moment: 'moment'
      }),
      new webpack.DefinePlugin({
        ENV_TEST: (JSON.stringify(process.env.NODE_ENV) === 'test') ? true : false
      }),
      new webpack.DefinePlugin({
        APP_VERSION: JSON.stringify(require('./package.json').version)
      })
    ],
    resolve: {
      root: path.resolve('./src'),
      modulesDirectories: ['node_modules'],
      extensions: ['', '.js', '.json', '.css']
    }
  };
```

Resolves #108

### CODE REVIEW

**Comment by urish** [comment]
Thanks, I will look into that in a few days, so we will have it ready for the next beta release

**Comment by aaronroberson** [comment]
Ok I will add the forked version to my project in the time being. Thanks

**Comment by Turanchoks** [comment]
Hi! Any plans on getting this merged?

**Comment by urish** [comment]
There is a plan to have a working solution for webpack, but we have to made sure it doesn't break other use cases (browserify, require.js, system.js, etc)

**Comment by urish** [comment]
Thanks for your time!

This is partially resolved by commit  919882e (see #261), and seems like it doesn't work for all users anyway (see #253), so closing.

**Pull request closed without merging**
