### PR TITLE
Upgraded to use both UTC offset timezones and named timezones.

### PR DESCRIPTION
**Pull request by DiegoZoracKy**
applyTimezone upgraded to accept UTC offset timezone, using the .zone setter from moment.

### CODE REVIEW

**Comment by urish** [comment]
Thanks!

Looks good in general, though, it seems like the method of distinguishing between timezone names and offsets would miss some timezone names that do not include a slash character, such as "EST". Can you please fix that and update the PR? 

thx!

**Comment by DiegoZoracKy** [comment]
You are correct. I had to do this in a hurry (working on a project) and i haven't thought so well about it before the pull. I created a new version of the code but it seems that it didn't went well with travis. I will try to take a look later.

**Comment by urish** [comment]
thanks man!

**Comment by DiegoZoracKy** [comment]
"There was an error while loading data, please try again" is the error shown by Travis. Maybe you can  re-run the test?

**Comment by urish** [comment]
I just re-ran it, seems to be failing:

https://travis-ci.org/urish/angular-moment/builds/72359159

Uri

**Comment by DiegoZoracKy** [comment]
Check

**Comment by urish** [comment]
looks great! 

One last thing - can you please add a test case for the UTC offset timezone feature?

thx!

**Comment by DiegoZoracKy** [comment]
Done!

**Comment by urish** [comment]
You are awesome, million thanks!

**Comment by DiegoZoracKy** [comment]
Nice! Soon i will have to make another PR for utilizing timezone at `amCalendar`

**Pull request merged**
