### PR TITLE
amCalendar upgraded to accept a timezone parameter

### PR DESCRIPTION
**Pull request by DiegoZoracKy**

### CODE REVIEW

**Comment by urish** [comment]
thanks!

**Comment by DiegoZoracKy** [comment]
Hey @urish, could you push a new tag so we can get the new merged updates from bower?

**Comment by urish** [comment]
@DiegoZoracKy yes, will do it today.

**Comment by DiegoZoracKy** [comment]
Thanks!
Em 28/07/2015 18:56, "Uri Shaked" <notifications@github.com> escreveu:

**Comment by urish** [comment]
Just released at 0.10.2

**Pull request merged**
