### PR TITLE
minor edit to the am-time-ago directive code snippet

### PR DESCRIPTION
**Pull request by Jkim55**
minor edit to the am-time-ago directive code snippet. Added .getTime() to ln 95 of readme

### CODE REVIEW

**Comment by Jkim55** [comment]
Hi!
After finally figuring out I needed utc to use the am-time-ago directive, I thought this edit might be useful for those reading documentation on the am-time-ago directive code snippet. :D 
I hope it's helpful!

Ji

**Comment by urish** [comment]
Hi @Jkim55 , thank you for your contribution. Can you please explain how adding `new Date().getTime()` helped in your case?

**Comment by Jkim55** [comment]
Thanks for accepting my pr! 👍

I used the angular-moment for a project I'm doing to learn angular. The project is to recreate a reddit like single page app and one of the parameters of the project is to display time as relative time from the current moment. 

So, I came upon angular-moment, but I found that the am-time-ago directive wasn't doing what I expected it to do. Maybe that's obvious to more experienced developers, but I'm a newbie. So, I researched it a bit and found that am-time-ago directive seems to wants the # in unix time. Since new Date () doesn't return milliseconds, I chained getTime() to convert it to milliseconds. 

Hopefully, this will help some other newbies or those who are just new to angular-moment a few minutes in their day. 🙌

**Comment by Jkim55** [comment]
opps- nevermind! Seems to work with the new Date, too. Maybe I made a typo!

**Comment by urish** [comment]
Thank you for your time. It is always inspiring to see newbies contributing and taking part in open source, and you seems to have a lot going on in your github account. Keep up the good work!

**Comment by Jkim55** [comment]
Thanks for kind words! I'm so appreciative of js dev community, which I found to be supportive & open. 👍

**Pull request closed without merging**
