### PR TITLE
Change from moment dependency to moment-timezone

### PR DESCRIPTION
**Pull request by kylecannon**
`moment-timezone` replaces `moment` when installed via npm ([installation instructions here](http://momentjs.com/timezone/docs/#/use-it/node-js/)). Due to the require statements asking for `moment` instead of `moment-timezone`, it's impossible to get `moment.tz` to be defined. Changing the package.json dependency from moment to moment-timezone brings back expected functionality when using tools such as browserify and webpack.

### CODE REVIEW

**Comment by urish** [comment]
Hi, thanks for the contribution!

This going to break a lot of existing code (not everyone uses browserify or webpack). 

Did you try requiring `moment-timezone` before requiring `angular-moment` and see if this does the trick?

**Comment by kylecannon** [comment]
I did. I've spent about two hours or more trying to come up with a workaround before coming to this solution. However, if others aren't webpack or browserify this doesn't affect them at all as it doesn't change the global injection (only amd and commonJS style) 

The tests still pass that were written for the global style includes since it's injected via a script tag.

**Comment by kylecannon** [comment]
The issue happens on [Line 719](https://github.com/urish/angular-moment/blob/master/angular-moment.js#L719) and [Line 721](https://github.com/urish/angular-moment/blob/c3f3361e49fc057ab38ad01f132c51a6037628f7/angular-moment.js#L721) which implicitly requires `moment` instead of `moment-timezone`.

**Comment by urish** [comment]
There are also require.js users. I believe this can still be worked around by using angular.js dependency injection and overriding the `moment` constant with a suitable implementation (e.g. the one returned by requiring `moment-timezone`).

Can you please have a look at it and see if this does the trick?

**Comment by kylecannon** [comment]
Well don't I feel like an idiot... one... simple... line of code.

Thank you!

Also, for some weird reason beta 5 doesn't throw the error that I am seeing in beta 4. So I will upgrade to beta 5 and also keep `ngModule.constant('moment', require('moment-timezone');` there as well incase.

**Comment by kylecannon** [comment]
Also, I appreciate the help and the fast response. Great library!

**Comment by urish** [comment]
Thanks Kyle!

Any chance you can send a PR with an update to `README.md` in favor of future users with the same need?

**Comment by kylecannon** [comment]
#235

**Comment by monove** [comment]
Is there any way of doing this without require?

**Pull request closed without merging**
